//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.HuskyCustom
{
    [Serializable]
    public class OdomNavigationFeedback : Message
    {
        public const string k_RosMessageName = "husky_custom_actions/OdomNavigation";
        public override string RosMessageName => k_RosMessageName;

        // feedback
        public float start_angle_turned;
        public float distance_moved;
        public float final_angle_turned;

        public OdomNavigationFeedback()
        {
            this.start_angle_turned = 0.0f;
            this.distance_moved = 0.0f;
            this.final_angle_turned = 0.0f;
        }

        public OdomNavigationFeedback(float start_angle_turned, float distance_moved, float final_angle_turned)
        {
            this.start_angle_turned = start_angle_turned;
            this.distance_moved = distance_moved;
            this.final_angle_turned = final_angle_turned;
        }

        public static OdomNavigationFeedback Deserialize(MessageDeserializer deserializer) => new OdomNavigationFeedback(deserializer);

        private OdomNavigationFeedback(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.start_angle_turned);
            deserializer.Read(out this.distance_moved);
            deserializer.Read(out this.final_angle_turned);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.start_angle_turned);
            serializer.Write(this.distance_moved);
            serializer.Write(this.final_angle_turned);
        }

        public override string ToString()
        {
            return "OdomNavigationFeedback: " +
            "\nstart_angle_turned: " + start_angle_turned.ToString() +
            "\ndistance_moved: " + distance_moved.ToString() +
            "\nfinal_angle_turned: " + final_angle_turned.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Feedback);
        }
    }
}
