//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.KinovaCustom
{
    [Serializable]
    public class OdomNavigationGoal : Message
    {
        public const string k_RosMessageName = "kinova_custom_actions/OdomNavigation";
        public override string RosMessageName => k_RosMessageName;

        // goal - 
        public Geometry.Pose2DMsg relative_goal_pose_2d;

        public OdomNavigationGoal()
        {
            this.relative_goal_pose_2d = new Geometry.Pose2DMsg();
        }

        public OdomNavigationGoal(Geometry.Pose2DMsg relative_goal_pose_2d)
        {
            this.relative_goal_pose_2d = relative_goal_pose_2d;
        }

        public static OdomNavigationGoal Deserialize(MessageDeserializer deserializer) => new OdomNavigationGoal(deserializer);

        private OdomNavigationGoal(MessageDeserializer deserializer)
        {
            this.relative_goal_pose_2d = Geometry.Pose2DMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.relative_goal_pose_2d);
        }

        public override string ToString()
        {
            return "OdomNavigationGoal: " +
            "\nrelative_goal_pose_2d: " + relative_goal_pose_2d.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Goal);
        }
    }
}
