//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.KinovaCustom
{
    [Serializable]
    public class OdomNavigationResult : Message
    {
        public const string k_RosMessageName = "kinova_custom_actions/OdomNavigation";
        public override string RosMessageName => k_RosMessageName;

        // result
        public Geometry.Pose2DMsg final_pose;

        public OdomNavigationResult()
        {
            this.final_pose = new Geometry.Pose2DMsg();
        }

        public OdomNavigationResult(Geometry.Pose2DMsg final_pose)
        {
            this.final_pose = final_pose;
        }

        public static OdomNavigationResult Deserialize(MessageDeserializer deserializer) => new OdomNavigationResult(deserializer);

        private OdomNavigationResult(MessageDeserializer deserializer)
        {
            this.final_pose = Geometry.Pose2DMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.final_pose);
        }

        public override string ToString()
        {
            return "OdomNavigationResult: " +
            "\nfinal_pose: " + final_pose.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Result);
        }
    }
}
