//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_Arm : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean Move_Target_Enable
        {
            get
            {
                return SteamVR_Actions.arm_Move_Target_Enable;
            }
        }
        
        public virtual SteamVR_Action_Boolean Confirm_Target
        {
            get
            {
                return SteamVR_Actions.arm_Confirm_Target;
            }
        }
        
        public virtual SteamVR_Action_Boolean Stop_Arm
        {
            get
            {
                return SteamVR_Actions.arm_Stop_Arm;
            }
        }
    }
}
