//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_Common : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean Switch_Control
        {
            get
            {
                return SteamVR_Actions.common_Switch_Control;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.common_Pose;
            }
        }
        
        public virtual SteamVR_Action_Boolean RadialMenu_Select
        {
            get
            {
                return SteamVR_Actions.common_RadialMenu_Select;
            }
        }
        
        public virtual SteamVR_Action_Boolean RadialMenu_Activate
        {
            get
            {
                return SteamVR_Actions.common_RadialMenu_Activate;
            }
        }
        
        public virtual SteamVR_Action_Vector2 RadialMenu_CursorPosition
        {
            get
            {
                return SteamVR_Actions.common_RadialMenu_CursorPosition;
            }
        }
        
        public virtual SteamVR_Action_Boolean Turn_Cam_Left
        {
            get
            {
                return SteamVR_Actions.common_Turn_Cam_Left;
            }
        }
        
        public virtual SteamVR_Action_Boolean Turn_Cam_Right
        {
            get
            {
                return SteamVR_Actions.common_Turn_Cam_Right;
            }
        }
        
        public virtual SteamVR_Action_Boolean Centre_Cam
        {
            get
            {
                return SteamVR_Actions.common_Centre_Cam;
            }
        }
        
        public virtual SteamVR_Action_Boolean Next_Tutorial
        {
            get
            {
                return SteamVR_Actions.common_Next_Tutorial;
            }
        }
        
        public virtual SteamVR_Action_Boolean Turn_Robot_To_Cam
        {
            get
            {
                return SteamVR_Actions.common_Turn_Robot_To_Cam;
            }
        }
    }
}
