//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_Base : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean Select_Target
        {
            get
            {
                return SteamVR_Actions.base_Select_Target;
            }
        }
        
        public virtual SteamVR_Action_Vector2 Rotate_Target
        {
            get
            {
                return SteamVR_Actions.base_Rotate_Target;
            }
        }
        
        public virtual SteamVR_Action_Boolean Confirm_Target
        {
            get
            {
                return SteamVR_Actions.base_Confirm_Target;
            }
        }
        
        public virtual SteamVR_Action_Boolean Stop_Robot
        {
            get
            {
                return SteamVR_Actions.base_Stop_Robot;
            }
        }
        
        public virtual SteamVR_Action_Boolean MoveForward
        {
            get
            {
                return SteamVR_Actions.base_MoveForward;
            }
        }
        
        public virtual SteamVR_Action_Boolean MoveBackward
        {
            get
            {
                return SteamVR_Actions.base_MoveBackward;
            }
        }
    }
}
